# Generated by Django 4.2.7 on 2024-01-01 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_lesson_progress_userlessonprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lessonReferenceNumber',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='number',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(default='Default lesson content'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='google_slide_embed_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='python_compiler_embed_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserLessonProgress',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.lesson'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'lesson')},
        ),
    ]
